theme: jekyll-theme-architect
title: Ildar Baimuratov
description: Associate professor at ITMO University
logo: https://avatars.githubusercontent.com/u/16117064?s=400&u=37f3e3c56b386a8f643d5be71b93c09639d7ca25&v=4
